(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1800)};
let done=new Set();try{done=new Set(JSON.parse(localStorage.getItem('admin-guide-progress')||'[]'))}catch{}
function update(){$$('[data-complete]').forEach(b=>{const yes=done.has(b.dataset.complete);b.classList.toggle('done',yes);b.textContent=yes?'✓ Đã qua cổng':b.dataset.complete==='8'?'Hoàn thành guideline':'Đánh dấu qua cổng'});const n=done.size;$('#progress-label').textContent=n+'/8 cổng';$('#progress-bar').style.width=(n/8*100)+'%';$('#progress-message').textContent=n===8?'Đã hoàn thành checklist. Hãy lưu bằng chứng và xin duyệt thí điểm.':n?'Tiếp tục cổng '+Math.min(n+1,8)+'; không bỏ qua artifact và người duyệt.':'Bắt đầu bằng một quy trình nhỏ, ổn định và có chủ sở hữu.';localStorage.setItem('admin-guide-progress',JSON.stringify([...done]))}
$$('[data-complete]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.complete;done.has(id)?done.delete(id):done.add(id);update();toast(done.has(id)?'Đã ghi nhận cổng '+id:'Đã bỏ cổng '+id)}));
$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const t=$('#'+b.dataset.copy)?.innerText||'';let copied=false;try{if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(t);copied=true}}catch{}if(!copied){const area=document.createElement('textarea');area.value=t;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{copied=document.execCommand('copy')}catch{}area.remove()}toast(copied?'Đã sao chép prompt':'Hãy chọn văn bản và sao chép thủ công')}));
const menu=$('#menu'),nav=$('#mobile-nav');menu.addEventListener('click',()=>{const open=nav.hidden;nav.hidden=!open;menu.setAttribute('aria-expanded',String(open))});$$('#mobile-nav a').forEach(a=>a.addEventListener('click',()=>{nav.hidden=true;menu.setAttribute('aria-expanded','false')}));
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#reading').style.width=(h?scrollY/h*100:0)+'%'},{passive:true});update();
})();
