import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PUBLIC_DIR = path.join(__dirname, 'public');

// 1. Clean & create public directory
if (fs.existsSync(PUBLIC_DIR)) {
  fs.rmSync(PUBLIC_DIR, { recursive: true, force: true });
}
fs.mkdirSync(PUBLIC_DIR, { recursive: true });

// 2. Items to copy
const itemsToCopy = [
  'index.html',
  'slide.html',
  'admin-guide.html',
  'favicon.svg',
  'css',
  'js',
  'assets',
  'partials',
  'downloads',
  'starter'
];

for (const item of itemsToCopy) {
  const src = path.join(__dirname, item);
  const dest = path.join(PUBLIC_DIR, item);
  if (fs.existsSync(src)) {
    fs.cpSync(src, dest, { recursive: true });
  }
}

// 3. Bundle page modules into public/js/page-content.js
const pagesDir = path.join(__dirname, 'partials', 'pages');
if (fs.existsSync(pagesDir)) {
  const modules = {};
  const files = fs.readdirSync(pagesDir).filter(f => f.endsWith('.html')).sort();
  for (const file of files) {
    const id = file.replace(/\.html$/, '');
    modules[id] = fs.readFileSync(path.join(pagesDir, file), 'utf8');
  }
  const jsDest = path.join(PUBLIC_DIR, 'js');
  fs.mkdirSync(jsDest, { recursive: true });
  fs.writeFileSync(
    path.join(jsDest, 'page-content.js'),
    `/* Generated by build.js */\nwindow.PAGE_MODULES = ${JSON.stringify(modules)};\n`
  );
}

console.log(`✅ Build completed! All clean static assets are ready in: public/`);
